In [1]:
import numpy as np
from Generator import Generator
import random
import csv

In [2]:
generator = Generator('example.csv') # filename with data

In [3]:
generator.generate(1000) # generates arg number of examples
generator.scale(0.5,2.5) # scales ingredients individually between min and max arg values
recipes = generator.recipes # recipes
quant = generator.quant # quantity of ingredients

In [4]:
print(recipes)
print(quant)

[[[  0.53   1.59   1.06 ...   2.12   0.53   0.53]
  [  9.32  13.98 125.82 ...  13.98  11.65  11.65]
  [  6.99  18.64  13.98 ...   4.66   6.99   4.66]
  ...
  [  0.     0.     0.   ...   0.     0.     0.  ]
  [  0.     0.     0.   ...   0.     0.     0.  ]
  [  1.49  99.83   8.94 ...   4.47  11.92   4.47]]

 [[  0.57   1.71   1.14 ...   2.28   0.57   0.57]
  [  6.52   9.78  88.02 ...   9.78   8.15   8.15]
  [  1.71   4.56   3.42 ...   1.14   1.71   1.14]
  ...
  [  6.96   6.96   4.64 ...  13.92  11.6    9.28]
  [  4.9    9.8    9.8  ... 215.6   14.7    4.9 ]
  [  1.04  69.68   6.24 ...   3.12   8.32   3.12]]

 [[  2.08   6.24   4.16 ...   8.32   2.08   2.08]
  [  9.04  13.56 122.04 ...  13.56  11.3   11.3 ]
  [  6.39  17.04  12.78 ...   4.26   6.39   4.26]
  ...
  [  5.52   5.52   3.68 ...  11.04   9.2    7.36]
  [  3.4    6.8    6.8  ... 149.6   10.2    3.4 ]
  [  1.42  95.14   8.52 ...   4.26  11.36   4.26]]

 ...

 [[  0.     0.     0.   ...   0.     0.     0.  ]
  [  0.     0.     0